version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "9000:8080"  # 외부에서 9090 포트로 접근하여 내부의 8080 포트에 연결
      - "50000:50000"  # Jenkins master와 agent 간의 통신 포트
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # 호스트의 Docker 소켓을 Jenkins 컨테이너에 마운트
      
volumes:
  jenkins:
